apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: weatherforecast-csharp
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=weatherforecast-csharp"
spec:
  type: service
  lifecycle: experimental
  owner: default-team
  dependencyOf:
    - component:meteorologist
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: weatherforecast-api
  description: Retrieve weather forecast per province
spec:
  type: openapi
  lifecycle: production
  owner: default-team
  #system: artist-engagement-portal
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Weather Forecast API
      license:
        name: MIT
    servers:
      - url: https://weatherforecast-csharp.tap.aks.lekeakinsanya.com
    paths:
      /WeatherForecast/Provinces:
        get:
          summary: List weather projections for all provinces
      /WeatherForecast/Provinces/{Province}:
        get:
          summary: Get weather projections for a specific province
