apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: weatherforecast-csharp
  labels:
    app.kubernetes.io/part-of: weatherforecast-csharp
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: weatherforecast-csharp
spec:
  template:
    metadata:
      annotations:
        conventions.apps.tanzu.vmware.com/applied-conventions: ""
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: weatherforecast-csharp
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: weatherforecast-csharp
    spec:
      containers:
      - env:
        - name: NAME
          value: Cartographer gitops ninja
        image: leke213.azurecr.io/supplychain-output-images/weatherforecast-csharp-default@sha256:40861d9a793cb310917514a85baed8e7945d01acea23a597f7559ff71c255cb7
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

