apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: weatherforecast-csharp
  labels:
    app.kubernetes.io/part-of: weatherforecast-csharp
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: weatherforecast-csharp
spec:
  template:
    metadata:
      annotations:
        conventions.apps.tanzu.vmware.com/applied-conventions: ""
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: weatherforecast-csharp
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: weatherforecast-csharp
    spec:
      containers:
      - env:
        - name: NAME
          value: Cartographer gitops ninja
        image: leke213.azurecr.io/supplychain-output-images/weatherforecast-csharp-default@sha256:7aa1cbf1d634428fdbfc63a857d65de235b76c0eeb68ea7980f4ca8dabc835ce
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

