apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: weatherforecast-csharp
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: weatherforecast-csharp
spec:
  serviceAccountName: workload-service-account
  source:
    git:
      url: https://github.com/akinsanyaleke/weatherforecast-csharp
      ref:
        branch: main
  env:
    - name: NAME
      value: "Cartographer gitops ninja"
  params:
    - name: containerPort
      value: 8080
    - name: language
      value: dotnet

